title: Packt Publishing
description: Packt Publishing Github Page
author: Packt Publishing
github: https://github.com/PacktPublishing
about: Providing books, eBooks, video tutorials, and articles for IT developers, administrators, and users.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook-f
      link: "https://www.facebook.com/PacktPub/"
    - icon: fa-twitter
      link: "https://twitter.com/PacktPub"
    - icon: fa-linkedin-in
      link: "https://www.linkedin.com/company/packt-publishing/"
    - icon: fa-youtube
      link: "https://www.youtube.com/user/packt1000/featured"
    - icon: fa-github
      link: "https://github.com/PacktPublishing"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: Official Website
      url: https://www.packtpub.com/
    - text: Wiki
      url: https://en.wikipedia.org/wiki/Packt

url: "https://sabypackt.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
